[package]
name = "nue"
description = "Node installer, made properly."
version = "0.0.0"
edition = "2021"
rust-version = "1.79.0"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
ureq = { version = "2.9.7", features = ["json"] }
